(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[149,252,115,98],[0,252,147,113],[122,367,63,37],[0,0,300,250],[0,367,120,61],[266,252,70,125]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.nineteenbottomleft = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.nineteenbottomright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.nineteencrackers = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.nineteentable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.nineteentopleft = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.nineteentopright = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whitesquare = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A41UyMAAAgpjMAxrAAAMAAAApjg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whitesquare, new cjs.Rectangle(-158.9,-133,318,266), null);


(lib.squarebottomleftholidayplatters = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteenbottomleft();
	this.instance.parent = this;
	this.instance.setTransform(-60,-52.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.squarebottomleftholidayplatters, new cjs.Rectangle(-60,-52.5,115,98), null);


(lib.square = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#99CC33").ss(1,1,1).p("A3UxxMAupAAAMAAAAjjMgupAAAg");
	this.shape.setTransform(0.2,0.5,1.003,1.096);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("A3URxMAAAgjhMAupAAAMAAAAjhg");
	this.shape_1.setTransform(0.2,0.5,1.003,1.096);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f().s("#99CC33").ss(1,1,1).p("AAASIMAAAgkP");
	this.shape_2.setTransform(-149.9,-9.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-150.9,-126.1,301.9,252.4);


(lib.shopnow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AASAjIgSg0IgRA0IgOAAIgYhGIAPAAIAQA1IABAAIAQg1IAPAAIARA1IAQg1IAPAAIgXBGg");
	this.shape.setTransform(28.8,1.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgOAjQgHgDgFgFQgFgFgDgHQgDgHAAgIQAAgHADgIQADgGAFgFQAFgFAHgDQAHgCAHAAQAIAAAHACQAHADAFAFQAGAFACAGQADAIAAAHQAAAIgDAHQgCAHgGAFQgFAFgHADQgHACgIAAQgHAAgHgCgAgJgXQgFACgDAEQgDAEgBAEQgCAFAAAEQAAAFACAEQABAFADAEQADAEAFACQAEACAFAAQAGAAAEgCQAFgCADgEQADgEABgFQACgEAAgFQAAgEgCgFQgBgEgDgEQgDgEgFgCQgEgCgGAAQgFAAgEACg");
	this.shape_1.setTransform(18.4,1.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AASAkIAAgmIgBgIIgCgHIgFgFQgDgBgFgBQgHAAgGAHQgGAGABALIAAAkIgPAAIAAg2IAAgIIAAgIIANAAIABAHIAAAFIABAAIADgFIAGgFIAGgDIAGAAQAIAAAEABQAGADACAEQAEAEACAFQABAGAAAFIAAArg");
	this.shape_2.setTransform(9.5,1.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AglA3IAAhrIAOAAIAAALIABAAQADgFAHgEQAGgDAIAAQAIAAAHACQAGADAFAFQAFAFACAHQADAHAAAIQAAAHgDAIQgCAGgFAEQgFAFgGAEQgHACgIAAQgHABgGgEQgHgDgEgGIgBAAIAAAvgAgJgoQgFACgDAEIgFAIIgBAKQAAAFABAEQACAFADADQADAEAFACQAEACAFAAQAFAAAFgCQAEgDADgEQADgCACgFIABgJIgBgKQgCgEgDgEQgDgEgEgCQgFgCgFAAQgFAAgEACg");
	this.shape_3.setTransform(-3.2,3.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgOAjQgHgDgFgFQgFgFgDgHQgDgHAAgIQAAgHADgIQADgGAFgFQAFgFAHgDQAHgCAHAAQAIAAAHACQAHADAFAFQAGAFACAGQADAIAAAHQAAAIgDAHQgCAHgGAFQgFAFgHADQgHACgIAAQgHAAgHgCgAgJgXQgFACgDAEQgDAEgBAEQgCAFAAAEQAAAFACAEQABAFADAEQADAEAFACQAEACAFAAQAGAAAEgCQAFgCADgEQADgEABgFQACgEAAgFQAAgEgCgFQgBgEgDgEQgDgEgFgCQgEgCgGAAQgFAAgEACg");
	this.shape_4.setTransform(-12.7,1.4);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AASA5IAAgoIgBgIQgBgEgCgDQgBgCgDgCQgEgBgEAAQgEAAgDABQgEACgCACQgGAGAAALIAAAmIgOAAIAAhxIAOAAIAAA1IABAAQACgFAGgEIAHgCIAGgBQAHAAAFACQAFACADAEIAFAIQACAGAAAGIAAAsg");
	this.shape_5.setTransform(-21.6,-0.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgUA0QgJgEgGgHIALgKQAFAFAFAEQAHADAHAAIAHgBQADgBADgCQADgCADgEQABgDAAgFQAAgFgBgDQgCgDgEgCIgIgEIgJgEIgKgDQgFgBgEgEQgDgDgDgFQgCgFAAgHQAAgIADgGQADgGAFgDQAGgEAGgCQAHgCAFAAIAJABIAIADQAJADAFAFIgLALQgDgFgGgCQgEgDgIAAIgGABIgGADIgGAFQgBAEAAAEQAAAEABADIAFAFIAHAEIAHADIALADIALAFQAEADADAGQADAFAAAIQAAAIgEAGQgCAGgGAEQgEAEgIACQgGACgGAAQgKAAgKgEg");
	this.shape_6.setTransform(-30.4,-0.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.shopnow, new cjs.Rectangle(-36.6,-11.7,73.2,22.4), null);


(lib.rectanglenineteen = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AnLCpQhGAAgygyQgxgxAAhGIAAAAQAAhFAxgyQAygxBGAAIOXAAQBGAAAxAxQAyAyAABFIAAAAQAABGgyAxQgxAyhGAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.rectanglenineteen, new cjs.Rectangle(-62.8,-16.8,125.8,33.8), null);


(lib.readyserveshrimp = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AhFBhQgHgCAAgGQAAgFAGgCIAIgEQACgDACgLQABgLAAgkIAAgXQAAgmgCgLQgBgMgDgCIgHgCQgIgDAAgEQAAgDACgDQADgCAGgCIAUgHQAJgDAFABQAEAAACACQABABAAAGIAAAHIABADIAAAAIAGgDIAFgFQAJgGAHgDQAJgDAIAAQAaAAARATQARAUAAAeQAAAhgTAXQgTAVgdAAQgMAAgEgDQgFgEAAgFQAAgEACgCQADgCAEAAIADABIAFAAQAQAAAJgNQAKgNAAgVQAAgZgLgPQgKgOgQAAQgOgBgJAJQgIAIAAAWIAABaIABANQAAAGACACQACACAGACIAGACIADACIABAFQAAAFgIACQgJACgUABQgUgBgIgCg");
	this.shape.setTransform(-13.3,22.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AhzBGQgHgCAAgGQAAgFAHgDIAEgBQADgCACgFQABgFAAgKIAAgKIAAgMIAAgIQAAgZgBgIQgBgIgDgCIgGgDQgJgCAAgFQAAgDACgCIAJgFIAVgIIAPgCQADAAACACQACADAAAFIAAAHIAAACIABABIABABIAAgBIAAAAIAEgDIACgBQARgQARAAQAGAAAHACQAGACAGAEQAEADAFAHIAHAHQACgBAEgEIAGgGQAKgJAGgCQAHgDAJAAQAQAAAMAHQANAGAFANQAHANAAAoIAAAPIAAAHIAAAGQgBAJACAEQACADADACIAEABQAHADAAAFQAAAGgHACQgHACgVAAQgVAAgHgCQgHgCAAgFQAAgFAIgEIAEgCQAFgCABgHIABgYQAAgpgGgLQgGgMgPAAQgQAAgHAPQgIAOABAiIAAAIQAAAPACAFQABAFADACIAEABQAHADAAAFQAAAGgGACQgHACgWAAQgTAAgGgCQgIgCAAgFQAAgGAIgCIAFgDQADgCACgFQABgGAAgQQAAgsgGgMQgGgMgPAAQgIABgGAEQgHAFgEAHQgDAHgBALIgBAmIABASQABAEADACIAGADQAGACABAGQgBAFgGACQgIADgTAAQgVAAgHgDg");
	this.shape_1.setTransform(-34.4,20.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgYBlQgIgCAAgGQAAgFAHgDIAEgBQAEgCABgFQACgFAAgKIAAgKIAAgMIAAgOQAAgWgCgHQgBgGgCgCIgHgDQgJgCAAgFQAAgDADgCIAJgGIAVgHIAOgCQAEAAACACQACAEAAAGIAAAIIgBAHIgBAjIAAABIAAAjIABATQABAGADABIAGADQAHACAAAGQAAAFgHACQgHADgTAAQgUAAgHgDgAgRhHQgGgFAAgIQAAgIAHgFQAHgGAJAAQAJAAAGAFQAGAGAAAHQAAAIgHAGQgHAFgJAAQgJAAgGgFg");
	this.shape_2.setTransform(-51.5,17);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AgqBGQgHgCAAgGQAAgFAHgDIADgBQAEgCACgFQABgFAAgKIAAgKIAAgMIAAgIQAAgZgBgIQgBgIgDgCIgHgDQgJgCAAgFQAAgDADgCQADgDAGgDIATgFIANgDQAHAAACATIAAADIABABQAHgMAIgGQAIgGAIAAQAKAAAGAGQAGAGAAAKQAAAKgFAFQgEAGgIAAIgIgBIgGgFIgDgFQAAgBAAgBQgBAAAAgBQgBAAAAAAQAAgBgBAAQgKAAgEAOQgDANAAArQAAANABAFQACAHAEABIAFACQAJADAAAGQAAAFgIACQgIADgTAAQgVAAgHgDg");
	this.shape_3.setTransform(-60.5,20.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AAUBmQgIgCABgFQgBgGAIgCIAFgDQAEgCABgGIABgVQAAgugGgLQgFgLgPAAQgHAAgHAEQgHAFgDAHQgDAGgCALIgBAnQAAAOABAFQABAEADACIAFADQAIACgBAGQAAAFgGACQgHACgSABQgXgBgHgCQgHgDABgFQgBgFAHgDIAEgBQAEgCABgGQACgHAAgPIAAgXIAAgWIgBhAQgBgPgCgEQgCgBgIgCQgJgDAAgFQABgEADgDQADgDANgEIAPgEIAMgBQAGAAABACQACADAAAGIAAAGIgBA5IAAAHIAAADIACABIAEgCIAFgHQAHgGAIgEQAHgEAJABQAYAAAMAPQAMAQAAAgIAAAMIAAAaIAAAIQAAAIACACQACAEACACIAEABQAIADgBAFQABAFgIADQgGACgXABQgTgBgGgCg");
	this.shape_4.setTransform(-75,16.9);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgjBnQgPgEgKgGQgGgDgEgMQgDgNAAgQQAAgGACgEQACgDAFAAQAHAAAHANIADAGQAJAQALAHQALAHAOAAQAPAAALgJQALgJAAgOQAAgUgqgSIgEgCQgjgOgLgNQgLgNAAgUQAAgZASgRQATgQAeAAIARABIATAFIAGgEIAFgBQADAAADACIAGAHQAFAJACAJQADAKAAAHQAAAFgCACQgCADgEAAQgIAAgHgKIgCgDQgIgLgKgFQgJgFgMAAQgPAAgJAIQgJAHAAANQAAAMAHAHQAIAIAeANIAGADQAZAKALAKQAIAHAEAJQAEAKAAALQAAAdgUARQgUAQgkAAQgRAAgQgDg");
	this.shape_5.setTransform(-91.5,17.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABgBAAAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_6.setTransform(92.1,-13.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgPA7QgIgNgTgvIgJgVQgKgbgHgDIgDgCQgJgDAAgFQAAgGAIgCQAGgCAYgBQATABAHACQAHACAAAGIgBAEIgDACIgEADQgHACAAADIAEALIALAcIALAbQADAHACgBQACAAACgDIAHgNIAPgjQAFgOAAgFIgBgEIgDgEIgEgCQgHgCAAgEQAAgGAHgCQAGgCASgBQAPABAGACQAGACAAAFQAAAGgIACIgFACQgGADgMAcIgEAJIgGANQggBJgIABQgHgBgIgOg");
	this.shape_7.setTransform(77.3,-13.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgqBHQgHgDAAgGQAAgFAHgCIADgCQAEgCACgFQABgEAAgMIAAgJIAAgLIAAgJQAAgZgBgIQgBgIgDgCIgHgCQgJgDAAgFQAAgDADgDQADgCAGgCIATgHIANgCQAHAAACATIAAADIABAAQAHgLAIgGQAIgGAIAAQAKAAAGAGQAGAGAAAKQAAAKgFAGQgEAFgIAAIgIgBIgGgEIgDgGQAAgBAAgBQgBAAAAgBQgBAAAAAAQAAAAgBAAQgKAAgEANQgDAOAAAqQAAAMABAHQACAGAEACIAFACQAJACAAAGQAAAFgIADQgIACgTAAQgVAAgHgCg");
	this.shape_8.setTransform(64.7,-13.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABgBAAAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_9.setTransform(51.5,-13.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AgjBnQgPgEgKgGQgGgDgEgMQgDgNAAgQQAAgGACgEQACgDAFAAQAHAAAHANIADAGQAJAQALAHQALAHAOAAQAPAAALgJQALgJAAgOQAAgUgqgSIgEgCQgjgOgLgNQgLgNAAgUQAAgZASgRQATgQAeAAIARABIATAFIAGgEIAFgBQADAAADACIAGAHQAFAJACAJQADAKAAAHQAAAFgCACQgCADgEAAQgIAAgHgKIgCgDQgIgLgKgFQgJgFgMAAQgPAAgJAIQgJAHAAANQAAAMAHAHQAIAIAeANIAGADQAZAKALAKQAIAHAEAJQAEAKAAALQAAAdgUARQgUAQgkAAQgRAAgQgDg");
	this.shape_10.setTransform(35.7,-16.7);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgiANQgBgCAAgEIABgGIADgIQACgDACgBQACgCAGAAIAHAAIAMABIAYgBIAEgBQAEAAADACQABACAAADQAAAHgEAHQgEAHgHAAIgHAAIgIAAIgfABIgCAAQgFAAgCgCg");
	this.shape_11.setTransform(22.6,-13.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AgzA1QgUgVAAgfQAAggAVgVQAVgVAfAAQAfAAAUAUQATAUAAAfQAAAggVAWQgVAWgeAAQgfAAgUgVgAgbgqQgIAMAAATQAAAbAMATQAMATAQAAQAOAAAJgMQAIgLAAgUQAAgagMgTQgMgTgQAAQgOAAgJALg");
	this.shape_12.setTransform(9.8,-13.6);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AgHBVQgHgCgFgEQgFgFgCgIQgCgIAAgVIAAhMIgNAAIgEgBIgCgDIAAgDQAAgGAPgMIAGgFIAGgFQAOgNAGAAIADABQABABAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAbIAgAAQADAAACABQABABAAAEIAAAEQAAAEgBABQgCABgDAAIgdAAIgDACIAAADIAABGQAAASADAFQADAEAIABQAFgBAHgCIAJgCQADAAADACQAAAAABABQAAAAAAABQAAAAABABQAAABAAAAQAAAIgMAIQgNAHgPAAQgIAAgHgDg");
	this.shape_13.setTransform(-3.2,-15);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AgiANQgBgCAAgEIABgGIADgIQACgDACgBQACgCAGAAIAHAAIAMABIAYgBIAEgBQAEAAADACQABACAAADQAAAHgEAHQgEAHgHAAIgHAAIgIAAIgfABIgCAAQgFAAgCgCg");
	this.shape_14.setTransform(-13.2,-13.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AhBBeQgHgGAAgJQAAgHAFgFQAFgFAHAAIAHABIAEADIAEAFQADAGADAAQAHAAAIgKQAHgLAAgLQAAgMgKgXIgBgDIgXgxIgNgcQgCgFgJgEQgFgCgBgCQgCgCAAgDQAAgGAHgCQAIgDAVAAQAUAAAHACQAHADAAAFIAAAFIgDACIgFADQgGACAAACIADALIAMAdIAKAaQAEAHACAAQACAAADgHIAJgWIALgcQADgKAAgEQAAgEgIgFQgIgEAAgEQAAgFAHgCQAGgCAQAAQARAAAGACQAGADAAAFQAAAGgIACIgGACQgIAEgJAYIgEALIgSAtQgYA7gOASQgPASgVAAQgKAAgHgGg");
	this.shape_15.setTransform(-25,-10.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("Ag9BWQgRgTgBgfQAAgjAUgUQATgWAfAAIAJABQAFABACADQACADAAAEQAAAIgJAAIgEgBIgDAAQgQAAgKANQgJAMAAAXQAAAXAKAQQALAPAPAAQAPAAAIgJQAIgIAAgQIAAgnIAAhBQAAgKgCgDQgBgEgGgCIgEgBQgIgDgBgFQABgEADgCQADgDALgEIAQgFIANgBQAGAAABACQACADAAAGIAAAIIgCBXIABA7QABAOADACIAKADQAIACAAAFQAAAGgWAHIgNAEIgLABQgEAAgCgCQgCgCAAgFIAAgHIAAgDIgBgBIgFADIgGAFQgIAGgHADQgIADgJAAQgbAAgQgTg");
	this.shape_16.setTransform(-40.2,-16.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AAZBDIgIgHIgGADQgRALgRAAQgVAAgMgMQgOgMAAgTQAAgXARgMQAQgNAeAAQAHAAAEADQADACAAAFQAAAIgJAAQgOAAgJAGQgJAHAAAMQAAAMAIAGQAHAHANAAQANAAAGgGQAGgGAAgPIAAg1QAAgNgFgHQgGgGgJAAQgHAAgGADQgGADgGAGIgCAEQgKALgJAAQgFAAgEgEQgEgDAAgHQABgNAQgJQAQgJAaAAQAPAAAMAEQALAEAGAIQAFAFACAJQACAJAAAUIAAAtIAAAMQACAEADABIAEABQAKADgBAFQAAAGgJAGQgKAFgNAAQgGAAgHgHg");
	this.shape_17.setTransform(-56.5,-13.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABgBAAAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_18.setTransform(-71.8,-13.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E46").s().p("AAfBHQgOgtgKgJQgJgKgOAAQgMAAAAgIQAAgJAJAAQAYAAALgJQALgJAAgUQAAgSgLgKQgMgKgVAAQgLAAgEACQgFABgBAEIgBANIgBAdIAAA+IABAqQABAKACACIAHADQAIAEAAAFQAAAHgHACQgIADgXAAQgWAAgIgDQgIgCAAgHQAAgFAJgEIAGgDQADgCACgRIABg9IgBg2QgCgUgBgDQgCgCgHgDQgIgDAAgGQAAgFAEgCQAFgDAJAAIAfAAIAcgBIAWAAQAgAAAQANQAQANAAAaQAAASgKAOQgLAOgUAFIAAACQAPACAJAKQAJAJAGAXIAEAPQAGAWAIAAIAEgBIAFAAQADAAACACQACACAAADQAAAHgIAEQgIAEgNAAQgdAAgJghg");
	this.shape_19.setTransform(-89.2,-16.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.readyserveshrimp, new cjs.Rectangle(-101.7,-35.8,203.5,71.6), null);


(lib.partystarted = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgkAsIgEgBQAAAAAAAAQgBgBAAAAQAAAAAAgBQAAAAAAgBIAAhPQAAAAAAAAQAAgBAAAAQAAgBABAAQAAAAAAAAQAAgBABAAQAAAAAAgBQABAAAAAAQABAAAAAAIAhAAIAIABIAJACQAJADAGAGQAHAGADAIIADAJIABAIQAAAKgEAIIgEAHIgGAHIgHAFIgIAEQgJADgIAAgAgXgaQgBAAAAABQAAAAAAABQgBAAAAABQAAAAAAAAIAAAwQAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABIADABIAQAAQAFAAAGgCQAFgDAFgDQAEgDACgGQADgFAAgHQAAgFgDgGQgCgFgEgEQgFgDgFgCQgGgCgFgBIgQAAQAAAAgBABQAAAAgBAAQAAAAAAAAQgBABAAAAg");
	this.shape.setTransform(77.1,-0.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgdAsIgDgBIgCgCIAAhRQABAAAAAAQAAgBAAAAQAAAAAAAAQABgBAAAAIACgBIA9AAIADACIABACIAAAEIAAACIgBADIgDACIgtAAIgCACIgBADIAAALIABAEIADABIAdAAIACABIABACIAAAEIAAACQAAAEgDAAIgdAAIgCACQgBAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAAAIAsAAQADABAAADIABAEIgBADIgBADIgCABg");
	this.shape_1.setTransform(67.8,-0.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAAAAAQgBAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_2.setTransform(59.5,-0.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AAWAtIgCgBIgCgBIgBgBIgPgXIgCgDIgEgBIgLAAIgDABIgBADIAAAWQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAIgEABIgDABIgDAAIgEgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIAAhQQAAgBAAAAQAAAAAAgBQAAAAAAAAQABgBAAAAIACgBIAlAAQAHAAAGACQAFADAFADQAEAEACAGQACAFAAAHQAAAIgCAEQgDAEgDADIgHAFQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAIAAACIAEAFIAFAHIAFAHIACAFIgBACIgDACIgDABIgDABgAgRgbQgBAAAAAAQgBABAAAAQAAABAAAAQAAABAAAAIAAAUQAAAAAAABQAAAAAAABQAAAAABABQAAAAABABIADAAIASAAIAGAAIAGgDQACgBABgDQACgDgBgEQAAgHgEgEIgGgCIgGgBIgSAAIgDABg");
	this.shape_3.setTransform(51.7,-0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AAjAsIgDAAIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAIgFgMIgBgCIgDgBIgdAAIgBABIgBAAIgBABIgBABIgFAMIgCACIgCAAIgDABIgCAAIgCAAIgDAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAlhSIACgCIACgBIAEAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAIAjBSIAAABIgBABIgDABgAAAgNIgBABIgBACIgCAEIgCAFIgCAFIgCADIAAACIAAACIACABIARAAIACgBIABgCIgCgDIgDgHIgDgHIgCgEIgCgBg");
	this.shape_4.setTransform(42.5,-0.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_5.setTransform(34.6,-0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgTAqQgKgDgHgHIgBgCIAAgBIABgDIADgDIADgCIADgBIAEABIAGAEIAHAEQAEABAGAAIAGAAIAHgCIAFgEQACgDAAgEQAAgDgCgCQgDgDgDgBIgKgBIgJgCIgKgCQgFgBgEgCQgEgDgDgEQgCgFAAgGQAAgHADgFQAEgFAFgEQAFgDAHgBIALgCIAJABIAIACIAJADIAHAFIAAACIABABIgBADIgDADIgDACIgEABIgCAAQgFgEgFgDQgFgCgGAAIgGAAIgGACIgEAEQgCACAAAEQAAAFAEACIAKADIANACQAHABAHACQAGADAEADQAFAFAAAJQgBAIgDAGQgEAFgFAEQgGADgHACIgMACQgKAAgJgEg");
	this.shape_6.setTransform(26.7,-0.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AAAAuIgDAAIgCAAIgCgCIAAgCIAAgeIgBgGIgCgEIgZgnIAAgBIABgCIACgCIAEgCIADgBIACABIACACIASAdIACABIABAAIACAAIACgBIARgdIACgCIAEgBIACAAIADACIAEACIABACIAAABIgBABIgZAnIgCAFIgBADIAAABIAAAfQgCADgCABg");
	this.shape_7.setTransform(14.7,-0.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_8.setTransform(7.1,-0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AAWAtIgCgBIgBgBIgCgBIgPgXIgCgDIgEgBIgLAAIgDABIgCADIABAWQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgDABIgDABIgDAAIgEgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAgBAAAAIAAhQQAAgBAAAAQAAAAAAgBQAAAAAAAAQABgBAAAAIACgBIAlAAQAHAAAGACQAFADAFADQAEAEACAGQACAFABAHQAAAIgEAEQgCAEgDADIgHAFQAAAAgBABQAAAAgBAAQAAABAAAAQAAABAAAAIAAACIADAFIAFAHIAFAHIACAFIgBACIgDACIgDABIgDABgAgRgbQgBAAAAAAQgBABAAAAQAAABAAAAQgBABAAAAIAAAUQAAAAABABQAAAAAAABQAAAAABABQAAAAABABIADAAIASAAIAHAAIAEgDQADgBABgDQABgDABgEQAAgHgGgEIgEgCIgHgBIgSAAIgDABg");
	this.shape_9.setTransform(-0.7,-0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AAjAsIgDAAIgEAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBgBAAAAIgFgMIgBgCIgDgBIgdAAIgBABIgBAAIgBABIgBABIgFAMIgCACIgCAAIgDABIgCAAIgCAAIgDAAIgCgBQgBAAAAAAQAAgBAAAAQgBAAAAAAQAAgBAAAAIAlhSIACgCIACgBIAEAAQAAABABAAQAAAAABAAQAAABAAAAQABABAAAAIAjBSIAAABIgBABIgDABgAAAgNIgBABIgBACIgCAEIgCAFIgCAFIgCADIAAACIAAACIACABIARAAIACgBIABgCIgCgDIgDgHIgDgHIgCgEIgCgBg");
	this.shape_10.setTransform(-9.9,-0.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgeAtQgEAAgCgEIAAhSIACgCIACgBIAmAAQAGAAAFACQAGACAEAEQAFADACAFQADAFAAAHIgBAEIgBAEQgDAIgGAEQgGAEgHABQgHABgHAAIgPAAIgBAAIgBABIgCADIAAAcIgCACIgCAAIgDABgAgSgbQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAOIACADIACABIAWAAIAFgBIAEgCQADgBABgDIABgFIgBgFIgDgDIgFgDIgEAAIgWAAQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAg");
	this.shape_11.setTransform(-18,-0.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AgdAsIgDgBIgCgCIAAhRQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIADgBIA9AAIACACIABACIAAAEIAAACIgBADIgCACIguAAIgCACIgBADIAAALIABAEIADABIAdAAIABABIABACIABAEIAAACQAAAEgDAAIgcAAIgEACQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAAAIAtAAQACABAAADIABAEIgBADIgBADIgCABg");
	this.shape_12.setTransform(-30.5,-0.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AAbAtIgEAAIgDgCIAAggQAAAAAAgBQAAAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAAAgBAAQAAgBgBAAQAAAAgBAAIgcAAQgBAAAAAAQgBAAgBABQAAAAAAAAQgBABAAAAQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIAAAeQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBABIgCAAIgEAAIgDAAIgDgBIgCgCIAAhTIACgCIADgBIADAAIADAAQAEAAABADIAAAcIABAEIADABIAeAAIAEgBQAAgBAAAAQABAAAAgBQAAAAAAgBQAAAAAAgBIAAgcQACgDADAAIAFAAIAEABIACACIAABTQgBADgDAAg");
	this.shape_13.setTransform(-39.9,-0.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_14.setTransform(-48.4,-0.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AACAsIgDAAIgEgBQAAAAgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBIAAhAQAAgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIgHAAIgHAAIgDAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAIgBgEIAAgDIABgDIABgCIADgBIA8AAQAAAAABAAQAAAAABAAQAAABABAAQAAAAAAABIABADIAAADIgBADIgBADIgCABIgSAAIgDABQgBAAAAAAQAAABAAAAQgBABAAAAQAAABAAAAIAABAIgBADIgCABg");
	this.shape_15.setTransform(-59.4,-0.3);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AgdAsIgDgBIgCgCIAAhRQAAAAABAAQAAgBAAAAQAAAAAAAAQABgBAAAAIADgBIA9AAIACACIAAACIAAAEIAAACIAAADIgCACIgtAAIgDACIgBADIAAALIABAEIADABIAdAAIABABIABACIABAEIAAACQAAAEgDAAIgcAAIgEACQAAAAAAABQAAAAgBABQAAAAAAABQAAAAAAABIAAAMIABAEQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAIAtAAQACABAAADIAAAEIAAADIgBADIgCABg");
	this.shape_16.setTransform(-66.9,-0.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AgHAtIgIgDIgIgDIgIgGIgFgHIgFgHQgDgJAAgKIAAgIIADgJQAEgJAGgGIAIgFIAIgEIAIgDIAJgBQAFAAAFACIAKACQAJAFAHAHIAAACIgBADIgDADIgDACIgDACIgEgCIgFgEIgHgFQgEgCgGAAQgFABgGACQgFACgEAEQgFAFgCAFQgCAGAAAFQAAAGACAGQACAFAFAEQAEAEAFADQAGACAFABIAGgBIAGgBIAGgEQACgBACgDIAAgBIgBgDIgDgBIgQAAIgCgBIgBgDIAAgDIAAgDIAAgDQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIAlAAIABABIABABQACADAAAFIAAADIgBAEIgHAMQgEAFgGAEQgFADgHACQgGACgHAAIgJgBg");
	this.shape_17.setTransform(-76.9,-0.3);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partystarted, new cjs.Rectangle(-83.9,-8.4,167.9,16.9), null);


(lib.partyperfectcrudite = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgKBKIgPgDIgEADIgFABIgDgBIgDgCQgEgEgEgLQgFgMAAgKQAAgFADgDQACgDAEAAQAHAAAGALIAGAJQAEAGAHADQAIADAHAAQAKAAAFgEQAGgFAAgIQAAgMgXgMIgJgEQgWgLgIgIQgHgJAAgOQAAgSAMgMQANgMAVAAIAJABIAKACIAHgDIAEgBQAHAAAHALQAHAMAAAMQAAAFgDADQgCADgEAAQgDAAgDgDQgDgDgFgHQgFgJgGgDQgGgDgHAAQgIAAgFAEQgFAFAAAHQAAAHAFAFQAFAFARAJIACABQAoASAAAXQAAAUgQANQgPAOgXAAg");
	this.shape.setTransform(85.9,20.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgXBmQgHgCAAgGQAAgFAGgCIAHgEQACgDABgIIABgcIAAgXIAAgaIAAgLQAAgjgBgLQgBgKgDgCIgJgDQgJgCAAgFQAAgEADgCQACgDALgDIATgGIANgCQAFAAABADQACADAAAGIAAALQgCAzAAAzIABAwQABALACACIAIAFQAHACAAAGQAAAFgHACQgHADgTAAQgVAAgGgDg");
	this.shape_1.setTransform(75.7,16.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AAJAPIgRgrQgIgVgHgDIgEgCQgJgDABgGQAAgFAGgDQAIgBAWAAQAUAAAHABQAGADAAAFIgBAFIgCADIgFACQgGACAAADIACAKIAMAdIANAbQACAGACABQACAAADgFIAHgMIAOgjQAGgOAAgEIgBgGIgEgDIgDgBQgHgDAAgFQAAgFAHgDQAFgBASAAQAPAAAHABQAFADABAFQAAAGgIACIgFACQgHADgNAeIgCAHIgHANQgfBKgKgBQgKABgYg7gAhTAIIgEgIIgJgZQgKgYgGgDIgEgCQgJgDABgGQgBgFAIgDQAHgBAXAAQAUAAAHABQAGADAAAFIgBAFIgDADIgEACQgGACAAADIADAMIALAbIAMAaQAEAIABAAQAFAAADgJIAGgKIACgFQADgBADAAQADAAACACQACACAAADQAAAEgEAIQgOAhgHAKQgHALgFAAQgKAAgchBg");
	this.shape_2.setTransform(60.4,20.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AgzA1QgUgVAAgfQAAggAVgVQAVgVAfAAQAfAAAUAUQATAUAAAfQAAAggVAWQgVAWgeAAQgfAAgUgVgAgbgqQgIAMAAATQAAAbAMATQAMATAQAAQAOAAAJgMQAIgLAAgUQAAgagMgTQgMgTgQAAQgOAAgJALg");
	this.shape_3.setTransform(40.5,20.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgKBnIgcgBIgNAAIgRABQgJgBgFgCQgGgDAAgFQAAgFAIgDQAIgEABgCQACgCABgWIABg3IgBg1QgBgVgCgCQgBgCgIgEQgIgDAAgFQAAgGAFgCQAEgCAJgBIAPAAIAQABIAdgBIAWAAQAfgBAQANQARANAAAYQAAATgMANQgMALgWAFQAcACAPANQAQAOAAAYQAAAagTAPQgTAPgjAAgAgVhSQgFABgBADQgCADgBAOIgBAoIAAA8IABAcQABAHACAEQABADAIACQAHACALAAQAXgBANgJQAMgKAAgTQAAgUgOgKQgOgJgZAAQgNAAAAgIQAAgKAMAAQATAAAMgJQAMgIAAgTQAAgSgLgJQgMgJgWAAg");
	this.shape_4.setTransform(22.6,17);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AguBWQgUgWAAgeQAAgiAVgUQAVgVAfAAQAcAAAQAPQAQAQAAAZQAAAJgDADQgCADgLAAIg2AAQgFAAgCgDQgDgCAAgDQAAgFADgCQACgBAFAAIAdAAIAHgBQABgBAAAAQABgBAAAAQAAgBAAAAQAAgBAAgBQAAgMgJgKQgJgJgNAAQgRAAgIAOQgIAOAAAVQAAAWALARQAMAQARAAQAKAAAIgDQAHgBAHgGIAFgDQAHgHAEAAQADAAACACQACADAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUgAgQg8QgDgFAAgDIABgCIADgDIAvgdIAEgCIAEgBQAEAAAEAGQAEAGAAAFQAAAFgJADIAAAAIgyAXIgCABIgCAAQgCAAgDgEg");
	this.shape_5.setTransform(-2.4,17);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgHBWQgHgDgFgFQgFgEgCgIQgCgHAAgWIAAhMIgNAAIgEAAIgCgEIAAgEQAAgEAPgNIAGgFIAGgFQAOgNAGAAIADACQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIAAAaIAgAAQADABACABQABABAAAEIAAADQAAAFgBABQgCABgDAAIgdAAIgDACIAAADIAABGQAAASADAFQADAFAIgBQAFAAAHgCIAJgCQADAAADACQAAAAABABQAAAAAAABQABAAAAABQAAABAAABQAAAHgMAHQgNAIgPAAQgIAAgHgCg");
	this.shape_6.setTransform(-14.9,18.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgYBlQgIgCAAgGQAAgFAHgDIAEgBQAEgCABgFQACgFAAgKIAAgKIAAgMIAAgOQAAgWgCgHQgBgGgCgCIgHgDQgJgCAAgFQAAgDADgCIAJgGIAVgHIAOgCQAEAAACACQACAEAAAGIAAAIIgBAHIgBAjIAAABIAAAjIABATQABAGADABIAGADQAHACAAAGQAAAFgHACQgHADgTAAQgUAAgHgDgAgRhHQgGgFAAgIQAAgIAHgFQAHgGAJAAQAJAAAGAFQAGAGAAAHQAAAIgHAGQgHAFgJAAQgJAAgGgFg");
	this.shape_7.setTransform(-24.1,17);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("Ag9BWQgSgTABgfQAAgjATgUQATgWAeAAIAKABQAEABADADQACADAAAEQAAAIgJAAIgEgBIgDAAQgQAAgJANQgKAMAAAXQAAAXALAQQAKAPAQAAQAOAAAIgJQAIgIAAgQIAAgnIAAhBQAAgKgCgDQgCgEgFgCIgDgBQgKgDABgFQAAgEADgCQAEgDAKgEIAQgFIANgBQAFAAADACQABADAAAGIAAAIIgBBXIAAA7QACAOACACIAKADQAIACgBAFQABAGgWAHIgOAEIgLABQgEAAgBgCQgCgCAAgFIAAgHIAAgDIgBgBIgEADIgHAFQgIAGgIADQgHADgJAAQgbAAgQgTg");
	this.shape_8.setTransform(-36,17);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AAfBIQgCgCAAgFIAAgKIAAAAIgBAAQgCAAgDADIgCACQgHAHgIAEQgIADgKAAQgLAAgKgEQgJgEgGgIQgHgIgDgLQgDgMAAgdIABgKIAAgKIAAgDQAAgMgCgDQgCgDgFgCIgFgCQgIgCAAgFQAAgEACgCQADgDAKgDIAUgFIAPgCQAEAAABADQACACAAAHIAAAFIgCA2QAAAcAGALQAGALAPAAQAPAAAHgPQAHgOAAgiIAAgLQAAgLgBgDQgCgDgFgCIgFgCQgIgCAAgFQAAgEACgCQADgCAKgEIATgFIAPgCQAEAAACACQACADAAAHIAAAIIgCA5IAAAZIABAJQABAGAHADIABAAIACABQAIACAAAFQAAADgCADQgDACgGACIgUAHIgPACQgEAAgCgCg");
	this.shape_9.setTransform(-53.5,20.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AgqBGQgHgCAAgGQAAgFAHgDIADgBQAEgCACgFQABgFAAgKIAAgKIAAgMIAAgIQAAgZgBgIQgBgIgDgCIgHgDQgJgCAAgFQAAgDADgCQADgDAGgDIATgFIANgDQAHAAACATIAAADIABABQAHgMAIgGQAIgGAIAAQAKAAAGAGQAGAGAAAKQAAAKgFAFQgEAGgIAAIgIgBIgGgFIgDgFQAAgBgBgBQAAAAAAgBQgBAAAAAAQAAgBgBAAQgKAAgEAOQgDANAAArQAAANABAFQACAHAEABIAFACQAJADAAAGQAAAFgIACQgIADgTAAQgVAAgHgDg");
	this.shape_10.setTransform(-67,20.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgVBjQgTgHgPgNQgQgPgJgVQgJgVAAgYQAAgUAGgRQAGgRALgOQAOgRAUgJQAUgJAXAAIARABIAcAGIADgBIALgCIAFABIADAEQAFAIADALQADALAAAIQAAAGgCADQgCADgFAAQgGAAgLgNIgJgKQgIgIgLgEQgLgEgOAAQgbAAgQATQgQATAAAhQAAAqAUAbQAVAbAeAAQANAAALgEQALgFAHgHIAHgIQAGgIAEAAQAEAAADAEQACAEAAAGQAAAOgEAHQgEAIgGAAIgBAAIgDgBQgNAHgNAEQgNADgPAAQgUAAgTgHg");
	this.shape_11.setTransform(-82.4,17.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AgHBVQgHgCgFgEQgFgFgCgIQgCgIAAgVIAAhMIgNAAIgEgBIgCgDIAAgDQAAgGAPgMIAGgFIAGgFQAOgNAGAAIADABQABABAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAbIAgAAQADAAACABQABABAAAEIAAAEQAAAEgBABQgCABgDAAIgdAAIgDACIAAADIAABGQAAASADAFQADAEAIABQAFgBAHgCIAJgCQADAAADACQAAAAABABQAAAAAAABQAAAAABABQAAABAAAAQAAAIgMAIQgNAHgPAAQgIAAgHgDg");
	this.shape_12.setTransform(70.6,-15);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AgsA2QgVgVAAgfQABggAVgWQAVgVAfAAQAXAAARAMQAQAMAAARQAAAGgEAEQgEAFgIAAQgHAAgEgEQgFgDgEgMQgFgKgFgEQgGgEgJAAQgQAAgJAMQgJAMAAAWQAAAZANAQQANAQAUAAQAHAAAHgCQAFgCAGgEIAGgEQAHgGAEAAQADAAADACQAAAAAAABQAAAAABABQAAAAAAABQAAABAAAAQAAAEgDAFQgDAFgFAEQgLAKgMAFQgMAEgPAAQgdAAgTgUg");
	this.shape_13.setTransform(58.3,-13.6);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABgBAAAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_14.setTransform(43.4,-13.6);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AgnBmQgHgCAAgGQAAgEAGgDIAEgBQADgCACgFQABgEAAgNIAAgNIAAhEIgQAAQgBAAAAAAQgBAAgBgBQAAAAgBAAQAAAAAAgBQgCgBAAgEIAAgEQAAgDACgCQAAAAABAAQAAgBABAAQAAAAABAAQABAAAAAAIAPAAIgBgMIAAgKQAAgVANgMQANgMAWAAQAQAAAKAHQALAHAAAMQAAAGgEAEQgEADgHAAQgEAAgEgCQgDgCgDgEIgDgFQgFgKgIAAQgFAAgDAEQgDADAAAGIADAPQACANABAKIAUAAQAEAAABABQACABAAAEIAAAEQAAAEgCABQgBACgEAAIgUAAIAABIIABAYQABAGADABIAGACQAIADAAAGQAAAFgHACQgHACgUAAQgUAAgHgCg");
	this.shape_15.setTransform(33.1,-16.9);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AgqBHQgHgDAAgGQAAgFAHgCIADgCQAEgCACgFQABgEAAgMIAAgJIAAgLIAAgJQAAgZgBgIQgBgIgDgCIgHgCQgJgDAAgFQAAgDADgDQADgCAGgCIATgHIANgCQAHAAACATIAAADIABAAQAHgLAIgGQAIgGAIAAQAKAAAGAGQAGAGAAAKQAAAKgFAGQgEAFgIAAIgIgBIgGgEIgDgGQAAgBAAgBQgBAAAAgBQgBAAAAAAQAAAAgBAAQgKAAgEANQgDAOAAAqQAAAMABAHQACAGAEACIAFACQAJACAAAGQAAAFgIADQgIACgTAAQgVAAgHgCg");
	this.shape_16.setTransform(22.7,-13.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABgBAAAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_17.setTransform(9.5,-13.6);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E46").s().p("AhJBlQgIgDAAgGQAAgGAJgDIAGgDQADgCACgRIABg9IgBg2QgCgUgBgEQgCgBgHgDQgIgDAAgGQAAgFAEgDQAFgDAJAAIAOAAIARABIAcgBIAWgBQAgAAAQAOQAQANAAAcQAAAdgTAQQgUAPgmAAQgNAAAAgKQAAgJALAAQASAAALgJQALgJAAgVQAAgUgLgKQgLgJgXAAQgKAAgEACQgFACgBADIgBANIgBAeIAAA+IABAoQABALACACIAHADQAIADAAAGQAAAGgHADQgIACgXAAQgWAAgIgCg");
	this.shape_18.setTransform(-6.2,-16.8);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E46").s().p("AgiANQgBgCAAgEIABgGIADgIQACgDACgBQACgCAGAAIAHAAIAMABIAYgBIAEgBQAEAAADACQABACAAADQAAAHgEAHQgEAHgHAAIgHAAIgIAAIgfABIgCAAQgFAAgCgCg");
	this.shape_19.setTransform(-20,-13.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E46").s().p("AhBBeQgHgGAAgJQAAgHAFgFQAFgFAHAAIAHABIAEADIAEAFQADAGADAAQAHAAAIgKQAHgLAAgLQAAgMgKgXIgBgDIgXgxIgNgcQgCgFgJgEQgFgCgBgCQgCgCAAgDQAAgGAHgCQAIgDAVAAQAUAAAHACQAHADAAAFIAAAFIgDACIgFADQgGACAAACIADALIAMAdIAKAaQAEAHACAAQACAAADgHIAJgWIALgcQADgKAAgEQAAgEgIgFQgIgEAAgEQAAgFAHgCQAGgCAQAAQARAAAGACQAGADAAAFQAAAGgIACIgGACQgIAEgJAYIgEALIgSAtQgYA7gOASQgPASgVAAQgKAAgHgGg");
	this.shape_20.setTransform(-31.8,-10.8);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E46").s().p("AgHBVQgHgCgFgEQgFgFgCgIQgCgIAAgVIAAhMIgNAAIgEgBIgCgDIAAgDQAAgGAPgMIAGgFIAGgFQAOgNAGAAIADABQABABAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAbIAgAAQADAAACABQABABAAAEIAAAEQAAAEgBABQgCABgDAAIgdAAIgDACIAAADIAABGQAAASADAFQADAEAIABQAFgBAHgCIAJgCQADAAADACQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAAIgMAIQgNAHgPAAQgIAAgHgDg");
	this.shape_21.setTransform(-44,-15);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E46").s().p("AgqBHQgHgDAAgGQAAgFAHgCIADgCQAEgCACgFQABgEAAgMIAAgJIAAgLIAAgJQAAgZgBgIQgBgIgDgCIgHgCQgJgDAAgFQAAgDADgDQADgCAGgCIATgHIANgCQAHAAACATIAAADIABAAQAHgLAIgGQAIgGAIAAQAKAAAGAGQAGAGAAAKQAAAKgFAGQgEAFgIAAIgIgBIgGgEIgDgGQAAgBAAgBQgBAAAAgBQgBAAAAAAQAAAAgBAAQgKAAgEANQgDAOAAAqQAAAMABAHQACAGAEACIAFACQAJACAAAGQAAAFgIADQgIACgTAAQgVAAgHgCg");
	this.shape_22.setTransform(-54.2,-13.7);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E46").s().p("AAZBDIgHgHIgGADQgRALgSAAQgVAAgNgMQgNgMABgTQAAgXAQgMQARgNAeAAQAGAAADADQAEACAAAFQAAAIgKAAQgNAAgJAGQgIAHAAAMQAAAMAHAGQAIAHAMAAQANAAAGgGQAGgGAAgPIAAg1QAAgNgGgHQgFgGgJAAQgHAAgGADQgGADgFAGIgEAEQgJALgJAAQgGAAgDgEQgDgDAAgHQAAgNAQgJQARgJAZAAQAQAAALAEQAMAEAFAIQAFAFABAJQACAJAAAUIAAAtIABAMQACAEADABIAEABQAJADAAAFQABAGgKAGQgKAFgMAAQgHAAgHgHg");
	this.shape_23.setTransform(-67.4,-13.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E46").s().p("AhJBlQgIgDAAgGQAAgGAJgDIAGgDQADgCACgRIABg9IgBg2QgCgUgBgEQgCgBgHgDQgIgDAAgGQAAgFAEgDQAFgDAJAAIAOAAIARABIAcgBIAWgBQAgAAAQAOQAQANAAAcQAAAdgTAQQgUAPgmAAQgNAAAAgKQAAgJALAAQASAAALgJQALgJAAgVQAAgUgLgKQgLgJgXAAQgKAAgEACQgFACgBADIgBANIgBAeIAAA+IABAoQABALACACIAHADQAIADAAAGQAAAGgHADQgIACgXAAQgWAAgIgCg");
	this.shape_24.setTransform(-83.4,-16.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.partyperfectcrudite, new cjs.Rectangle(-94.3,-35.8,188.6,71.6), null);


(lib.nineteentopright_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteentopright();
	this.instance.parent = this;
	this.instance.setTransform(-35,-62.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteentopright_1, new cjs.Rectangle(-35,-62.5,70,125), null);


(lib.nineteentopleft_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteentopleft();
	this.instance.parent = this;
	this.instance.setTransform(-60,-30.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteentopleft_1, new cjs.Rectangle(-60,-30.5,120,61), null);


(lib.nineteentable_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteentable();
	this.instance.parent = this;
	this.instance.setTransform(-150,-125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteentable_1, new cjs.Rectangle(-150,-125,300,250), null);


(lib.nineteencrackers_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteencrackers();
	this.instance.parent = this;
	this.instance.setTransform(-31.5,-18.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.nineteencrackers_1, new cjs.Rectangle(-31.5,-18.5,63,37), null);


(lib.logokale = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(130.4,59.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgUgDgIgEQgJgFAAgNQAAgKAGgHQAFgHAJAAIARAAQAKAAAFgLQADgKgBgXIAAl5QABgXgDgKQgFgLgKAAIgRAAQgJAAgFgHQgGgHAAgKQAAgNAJgFQAIgEAUgDQBegNBrAAQBNAAA1ASQA1ASAnAoQAlAlAVA5QATA4AABEQAABNgZA9QgZA+gwAlQglAegvAOQgxAOhEAAQhrAAhegNgAgvjrQgcAFgKALQgKAMAAAhIAAFjQAAAhAVALQANAHAnADQBNAEAshAQAqg/ABhwQAAhwgrg/Qgrg/hKAAIgdADg");
	this.shape_1.setTransform(62.2,30.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(81.2,88.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(52.4,88.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(22.6,88.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAvBeIghgxQgFgJgKAAIgtAAQgEAAgDADQgDACgBAFIABAwQAAAHgKACIgPAAQgNAAAAgLIAAi6QAAgIAJAAIBrAAQAgAAAUASQAVAUgBAgQAAAXgOAPQgIAJgPAJQgHAIAEAFIAiAyQAFAHgFAFQgEAEgPAAQgRAAgFgJgAg5g4IAAAuQABAFAEADQAEACAFAAIA+AAQAQAAALgHQALgKAAgPQAAgRgLgJQgLgJgQAAIg+AAQgOAAAAALg");
	this.shape_5.setTransform(-11.1,88.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAgBABAAQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-44.3,88.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBlQgFgDAAgFIgOhrQgCgHgFAAQgDAAgDAEIgxA+QgEAFgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBpQgCAKgTAAQgGAAgFgCQgGgDAAgGIAVixQACgJADgCQAEgFALAAQAKAAAFAIIA4BPQAFAIAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAJIAVC1QABAKgXAAQgFAAgFgCg");
	this.shape_7.setTransform(-78.1,88.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(14.6,-54.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDxQhFg2gYheIgBgDQgCgLgHABQgGgBgCALIgBABQgYBghGA2QhIA2hoAAQh+AAhMhQQhMhRAAiFQAAiGBMhRQBLhQCAAAQBpAABHA2QBHA3AXBgQACALAGgBQAHAAACgLIABAAQAXhgBGg2QBHg2BoAAQB/AABNBPQBMBQAACGQAACHhMBRQhNBQiBAAQhmAAhHg2gACniqQgpA/AABtQAABtApA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/gAmFiqQgoA/AABtQAABtAoA9QAoA+BIAAQBGAAApg/QAphAAAhrQAAhqgqhAQgpg/hHAAQhGAAgoA/g");
	this.shape_9.setTransform(-21,30.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-98.4,30.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIQAKgHAIAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(110.1,30.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAIQgNAIgQABQgTgBgKgIQgLgKgJgYIimm+QgKgZgHgIQgHgHgUgFQgOgBgFgGQgFgFAAgKQAAgXAdAAICvAAQAcAAAAAXQAAAMgHAEQgHAFgRABQgOACgGAEQgGAFAAALQAAAIADALIBzFGQACAFAFAAQAEgBACgFIA/i1QAIgZgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgEgGgEQgFgGAAgJQAAgaAdAAICnAAQAdAAAAAXQAAATgcAFQgRABgFAFQgGAFAAALQAAALAIAZIBfEsQACAFAEAAQAFgBABgFIBdk6QAEgLAAgJQAAgTgdgDQgbgCAAgWQAAgMAHgGQAIgGARAAIElAAQAVAAAIAGQAIAFAAAOQAAAKgGAHQgGAHgJAAIgQAAQgLAAgFAKQgCAJAAAZIAABuQAAAdAFAHQAGAGAXAAIB0AAQAXAAAHgHQADgEAAgGIABgfIAAhoQAAgbgDgHQgFgKgKAAIgQAAQgKAAgHgHQgGgHAAgKQAAgOAIgFQAJgGAWAAICaAAQAWAAAJAGQAJAFAAAOQAAAKgHAHQgGAHgJAAIgSAAQgEAAgEADQgFAEgBADQgDAKAAAYIAAF8QAAAYADALQABADAFAEQAEACAEAAIASAAQAJAAAGAIQAHAGAAAKQAAAOgJAGQgIAEgXAAIiaAAQgWAAgIgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIAQAAQAKABAFgKQADgIAAgbIAAh8IgBgdQAAgHgDgDQgHgIgXAAIh0AAQgXAAgGAHQgFAGAAAeIAACAQAAAZACAKQAFAKALgBIAQAAQAJAAAGAIQAGAGAAALQAAANgIAGQgIAEgVAAIiaAAQgWAAgJgEQgIgGAAgOQAAgKAGgGQAHgIAJAAIARAAQAEAAAFgCQAEgEABgDQADgIAAgbIAAl8QAAgwgkAEQgLABgHAJQgIAKgGAVIiHGzQgJAfgKAMQgLAKgTABQgTAAgLgKg");
	this.shape_12.setTransform(-74.6,-36.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDACgEQADgIAAgXIAAmAQAAgZgDgHQgDgMgLAAIgRAAQgKABgGgHQgHgHAAgKQAAgOAJgFQAJgGAWAAICcAAQAWAAAJAGQAJAFAAAOQAAAKgGAHQgHAHgJgBIgSAAQgOAAgDAMQgDAFAAAbIAAFkQAAAdACAJQACAJAIAFQAGAFALABQALACAaAAIAwAAQAvAAAPggIAIgQQAIgPAPAAQAMgBAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(69.2,-37.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgFAVgaAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(114.4,-37.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.logokale, new cjs.Rectangle(-175,-175,350,350), null);


(lib.HOLIDAYPLATTERS = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABAAAAgBQABAAAAgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape.setTransform(119.5,20.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgqBGQgHgCAAgGQAAgFAHgDIADgBQAEgCACgFQABgFAAgKIAAgKIAAgMIAAgIQAAgZgBgIQgBgIgDgCIgHgDQgJgCAAgFQAAgDADgCQADgDAGgDIATgFIANgDQAHAAACATIAAADIABABQAHgMAIgGQAIgGAIAAQAKAAAGAGQAGAGAAAKQAAAKgFAFQgEAGgIAAIgIgBIgGgFIgDgFQAAgBAAgBQgBAAAAgBQgBAAAAAAQAAgBgBAAQgKAAgEAOQgDANAAArQAAANABAFQACAHAEABIAFACQAJADAAAGQAAAFgIACQgIADgTAAQgVAAgHgDg");
	this.shape_1.setTransform(106.9,20.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AgzA1QgUgVAAgfQAAggAVgVQAVgVAfAAQAfAAAUAUQATAUAAAfQAAAggVAWQgVAWgeAAQgfAAgUgVgAgbgqQgIAMAAATQAAAbAMATQAMATAQAAQAOAAAJgMQAIgLAAgUQAAgagMgTQgMgTgQAAQgOAAgJALg");
	this.shape_2.setTransform(93.1,20.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AA1BkQgIgCAAgHQAAgFAJgEIAGgDQADgCABgGQABgGAAgUIAAgHIAAg8IgBgkIgSAvQgpBtgJAAQgFAAgIgPQgIgPgUguIgfhHIgBA3IgBAnIABAaQABAGACACIAGADQAJAEAAAFQAAAGgHADQgIADgRAAQgPAAgHgDQgIgDAAgGQAAgFAIgDQAIgEABgDQACgHACglQACgjAAgtIAAgFIgBgUQgCgFgDgCIgGgDQgKgDAAgGQAAgGAHgCQAGgCAVAAIAUABIAGABQACACALAZIAIAUIAEAKQAiBVACAAQAEAAAMgeQANgeASgyIACgJQAGgQAEgEQACgDAGgBIATgBQATAAAHACQAGACAAAGQAAAGgIADIgEACQgEACgCAGQgBAFAAAWIABBRQACAkABAFQABADAGADIADABIAGADQACACAAADQAAAHgIACQgIADgYAAQgVAAgIgDg");
	this.shape_3.setTransform(72.2,17.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AhWBWQgZgVAAggQgBgSAJgPQAIgNATgNIABgBQgHgHgCgGQgEgHAAgHQAAgXAQgOQARgPAaAAQASAAALAIQALAGAAAJQAAADgCACQgDADgEAAIgLgEQgKgEgIABQgLgBgHAIQgIAHAAANQAAAFACAFQACAEAEADQAEADAGADIAIADIADACIABABQAAAEgFAGQgFAFgFAAIgHgBIgJgEQgIAIgEAJQgEAKgBANQABAbARASQASARAbAAQAXAAAOgMQAOgLABgUQgBgMgFgHQgGgHgJAAQgKAAgHAFQgGAGAAAJIAAADIAAACIgBABIgDAAQgFAAgDgFQgDgEAAgGQAAgVA+gdIAEgCQAQgHAJgJQAJgIgBgLQAAgGgDgEQgEgCgHAAIgGAAIgFAAQgDAAgCgBQgCgDAAgDQAAgFAIgFQAIgEAMAAQAPAAAJAJQAJAHAAAPQAAASgPAPQgQAOggAMQANAEAIALQAGALAAAOQAAAKgEALQgFAKgHAJQgOAOgTAHQgUAIgYAAQgrAAgbgVg");
	this.shape_4.setTransform(40.1,17.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AgKBKIgPgDIgEADIgFABIgDgBIgDgCQgEgEgEgLQgFgMAAgKQAAgFADgDQACgDAEAAQAHAAAGALIAGAJQAEAGAHADQAIADAHAAQAKAAAFgEQAGgFAAgIQAAgMgXgMIgJgEQgWgLgIgIQgHgJAAgOQAAgSAMgMQANgMAVAAIAJABIAKACIAHgDIAEgBQAHAAAHALQAHAMAAAMQAAAFgDADQgCADgEAAQgDAAgDgDQgDgDgFgHQgFgJgGgDQgGgDgHAAQgIAAgFAEQgFAFAAAHQAAAHAFAFQAFAFARAJIACABQAoASAAAXQAAAUgQANQgPAOgXAAg");
	this.shape_5.setTransform(13.2,20.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_6.setTransform(-0.3,20.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AgHBWQgHgDgFgFQgFgEgCgIQgCgHAAgWIAAhMIgNAAIgEAAIgCgEIAAgEQAAgEAPgNIAGgFIAGgFQAOgNAGAAIADACQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIAAAaIAgAAQADABACABQABABAAAEIAAADQAAAFgBABQgCABgDAAIgdAAIgDACIAAADIAABGQAAASADAFQADAFAIgBQAFAAAHgCIAJgCQADAAADACQAAAAABABQAAAAAAABQABAAAAABQAAABAAABQAAAHgMAHQgNAIgPAAQgIAAgHgCg");
	this.shape_7.setTransform(-12.8,18.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AgYBlQgIgCAAgGQAAgFAHgDIAEgBQAEgCABgFQACgFAAgKIAAgKIAAgMIAAgOQAAgWgCgHQgBgGgCgCIgHgDQgJgCAAgFQAAgDADgCIAJgGIAVgHIAOgCQAEAAACACQACAEAAAGIAAAIIgBAHIgBAjIAAABIAAAjIABATQABAGADABIAGADQAHACAAAGQAAAFgHACQgHADgTAAQgUAAgHgDgAgRhHQgGgFAAgIQAAgIAHgFQAHgGAJAAQAJAAAGAFQAGAGAAAHQAAAIgHAGQgHAFgJAAQgJAAgGgFg");
	this.shape_8.setTransform(-22,17);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgKBnIgcgBIgNAAIgRABQgJgBgFgCQgGgDAAgFQAAgFAIgDQAIgEABgCQACgCABgWIABg3IgBg1QgBgVgCgCQgBgCgIgEQgIgDAAgFQAAgGAFgCQAEgCAJgBIAPAAIAQABIAdgBIAWAAQAfgBAQANQARANAAAYQAAATgMANQgMALgWAFQAcACAPANQAQAOAAAYQAAAagTAPQgTAPgjAAgAgVhSQgFABgBADQgCADgBAOIgBAoIAAA8IABAcQABAHACAEQABADAIACQAHACALAAQAXgBANgJQAMgKAAgTQAAgUgOgKQgOgJgZAAQgNAAAAgIQAAgKAMAAQATAAAMgJQAMgIAAgTQAAgSgLgJQgMgJgWAAg");
	this.shape_9.setTransform(-35.9,17);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AgXBmQgHgCAAgGQAAgFAGgCIAHgEQACgDABgIIABgcIAAgXIAAgaIAAgLQAAgjgBgLQgBgKgDgCIgJgDQgJgCAAgFQAAgEADgCQACgDALgDIATgGIANgCQAFAAABADQACADAAAGIAAALQgCAzAAAzIABAwQABALACACIAIAFQAHACAAAGQAAAFgHACQgHADgTAAQgVAAgGgDg");
	this.shape_10.setTransform(-57.6,16.9);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AgXBmQgHgCAAgGQAAgFAGgCIAHgEQACgDABgIIABgcIAAgXIAAgaIAAgLQAAgjgBgLQgBgKgDgCIgJgDQgJgCAAgFQAAgEADgCQACgDALgDIATgGIANgCQAFAAABADQACADAAAGIAAALQgCAzAAAzIABAwQABALACACIAIAFQAHACAAAGQAAAFgHACQgHADgTAAQgVAAgGgDg");
	this.shape_11.setTransform(-65.5,16.9);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AAZBDIgIgHIgFADQgSALgRAAQgVAAgMgMQgOgMAAgTQABgXAQgMQAQgNAeAAQAHAAAEADQADACAAAFQAAAIgJAAQgOAAgJAGQgJAHAAAMQAAAMAIAGQAHAHANAAQANAAAGgGQAGgGAAgPIAAg1QAAgNgFgHQgGgGgJAAQgHAAgGADQgGADgGAGIgDAEQgJALgJAAQgFAAgEgEQgDgDAAgHQAAgNAQgJQAQgJAaAAQAPAAAMAEQAMAEAFAIQAFAFACAJQABAJAAAUIAAAtIABAMQACAEADABIAEABQAKADgBAFQAAAGgJAGQgKAFgMAAQgHAAgHgHg");
	this.shape_12.setTransform(-76.7,20.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AhzBGQgHgCAAgGQAAgFAHgDIAEgBQAEgCABgFQABgFABgKIAAgKIAAgMIAAgIQgBgZgBgIQgBgIgDgCIgHgDQgIgCAAgFQAAgDADgCIAJgFIAUgIIAPgCQADAAACACQACADAAAFIAAAHIAAACIABABIABABIAAgBIABAAIADgDIABgBQASgQARAAQAHAAAGACQAGACAGAEQAEADAFAHIAHAHQACgBAEgEIAGgGQAJgJAHgCQAHgDAJAAQAQAAANAHQALAGAHANQAFANABAoIAAAPIAAAHIAAAGQAAAJABAEQACADADACIAEABQAHADAAAFQAAAGgHACQgHACgVAAQgVAAgHgCQgHgCAAgFQAAgFAIgEIAEgCQAEgCACgHIABgYQAAgpgGgLQgFgMgPAAQgRAAgHAPQgIAOAAAiIAAAIQABAPACAFQABAFADACIAEABQAHADAAAFQAAAGgGACQgHACgWAAQgTAAgGgCQgIgCABgFQgBgGAIgCIAFgDQADgCACgFQABgGAAgQQAAgsgGgMQgGgMgPAAQgIABgGAEQgHAFgEAHQgDAHgBALIgCAmIACASQABAEADACIAGADQAGACAAAGQAAAFgGACQgIADgSAAQgWAAgHgDg");
	this.shape_13.setTransform(-97.6,20.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("AgjBnQgPgEgKgGQgGgDgEgMQgDgNAAgQQAAgGACgEQACgDAFAAQAHAAAHANIADAGQAJAQALAHQALAHAOAAQAPAAALgJQALgJAAgOQAAgUgqgSIgEgCQgjgOgLgNQgLgNAAgUQAAgZASgRQATgQAeAAIARABIATAFIAGgEIAFgBQADAAADACIAGAHQAFAJACAJQADAKAAAHQAAAFgCACQgCADgEAAQgIAAgHgKIgCgDQgIgLgKgFQgJgFgMAAQgPAAgJAIQgJAHAAANQAAAMAHAHQAIAIAeANIAGADQAZAKALAKQAIAHAEAJQAEAKAAALQAAAdgUARQgUAQgkAAQgRAAgQgDg");
	this.shape_14.setTransform(-118.9,17.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AgOAsQgBgBgBAAQAAAAgBgBQAAAAAAgBQgBAAAAgBIAEgFIACgFIAJgPQACgHAAgDIgBgEIgEgCQgIgDgDgFQgDgFAAgIQgBgJAHgGQAFgHAJAAQAJAAAGAJQAHAIAAANQAAAJgFAKQgDAKgJAPIgHAMQgEADgCAAIgGgBg");
	this.shape_15.setTransform(83.5,-6.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AgKBKIgPgDIgEADIgFABIgDgBIgDgCQgEgEgEgLQgFgMAAgKQAAgFADgDQACgDAEAAQAHAAAGALIAGAJQAEAGAHADQAIADAHAAQAKAAAFgEQAGgFAAgIQAAgMgXgMIgJgEQgWgLgIgIQgHgJAAgOQAAgSAMgMQANgMAVAAIAJABIAKACIAHgDIAEgBQAHAAAHALQAHAMAAAMQAAAFgDADQgCADgEAAQgDAAgDgDQgDgDgFgHQgFgJgGgDQgGgDgHAAQgIAAgFAEQgFAFAAAHQAAAHAFAFQAFAFARAJIACABQAoASAAAXQAAAUgQANQgPAOgXAAg");
	this.shape_16.setTransform(73,-13.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AgqBHQgHgDAAgGQAAgFAHgCIADgCQAEgCACgFQABgEAAgMIAAgJIAAgLIAAgJQAAgZgBgIQgBgIgDgCIgHgCQgJgDAAgFQAAgDADgDQADgCAGgCIATgHIANgCQAHAAACATIAAADIABAAQAHgLAIgGQAIgGAIAAQAKAAAGAGQAGAGAAAKQAAAKgFAGQgEAFgIAAIgIgBIgGgEIgDgGQAAgBgBgBQAAAAAAgBQgBAAAAAAQAAAAgBAAQgKAAgEANQgDAOAAAqQAAAMABAHQACAGAEACIAFACQAJACAAAGQAAAFgIADQgIACgTAAQgVAAgHgCg");
	this.shape_17.setTransform(61.8,-13.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABgBAAAAQABAAAAgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_18.setTransform(48.6,-13.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E46").s().p("AgHBVQgHgCgFgEQgFgFgCgIQgCgIAAgVIAAhMIgNAAIgEgBIgCgDIAAgDQAAgGAPgMIAGgFIAGgFQAOgNAGAAIADABQABABAAAAQABAAAAABQAAAAAAABQAAAAAAABIAAAbIAgAAQADAAACABQABABAAAEIAAAEQAAAEgBABQgCABgDAAIgdAAIgDACIAAADIAABGQAAASADAFQADAEAIABQAFgBAHgCIAJgCQADAAADACQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAAIgMAIQgNAHgPAAQgIAAgHgDg");
	this.shape_19.setTransform(36.1,-15);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E46").s().p("AgHBVQgHgCgFgEQgFgFgCgIQgCgIAAgVIAAhMIgNAAIgEgBIgCgDIAAgDQAAgGAPgMIAGgFIAGgFQAOgNAGAAIADABQABABAAAAQAAAAABABQAAAAAAABQAAAAAAABIAAAbIAgAAQADAAACABQABABAAAEIAAAEQAAAEgBABQgCABgDAAIgdAAIgDACIAAADIAABGQAAASADAFQADAEAIABQAFgBAHgCIAJgCQADAAADACQAAAAABABQAAAAAAABQABAAAAABQAAABAAAAQAAAIgMAIQgNAHgPAAQgIAAgHgDg");
	this.shape_20.setTransform(26,-15);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E46").s().p("AAZBDIgHgHIgHADQgQALgSAAQgVAAgMgMQgNgMgBgTQAAgXARgMQARgNAdAAQAHAAADADQAEACAAAFQAAAIgJAAQgOAAgJAGQgJAHAAAMQABAMAHAGQAIAHAMAAQANAAAGgGQAGgGAAgPIAAg1QAAgNgGgHQgFgGgJAAQgHAAgGADQgGADgFAGIgDAEQgJALgKAAQgGAAgDgEQgDgDgBgHQAAgNARgJQARgJAaAAQAOAAAMAEQALAEAHAIQAEAFABAJQADAJAAAUIAAAtIABAMQABAEADABIAFABQAIADABAFQAAAGgKAGQgKAFgNAAQgGAAgHgHg");
	this.shape_21.setTransform(13.5,-13.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E46").s().p("AgXBmQgHgCAAgGQAAgFAGgCIAHgEQACgDABgIIABgcIAAgXIAAgaIAAgLQAAgjgBgLQgBgKgDgCIgJgDQgJgCAAgFQAAgEADgCQACgDALgDIATgGIANgCQAFAAABADQACADAAAGIAAALQgCAzAAAzIABAwQABALACACIAIAFQAHACAAAGQAAAFgHACQgHADgTAAQgVAAgGgDg");
	this.shape_22.setTransform(1.5,-16.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E46").s().p("AhJBlQgIgDAAgGQAAgGAJgDIAGgDQADgCACgRIABg9IgBg2QgCgUgBgEQgCgBgHgDQgIgDAAgGQAAgFAEgDQAFgDAJAAIAOAAIARABIAcgBIAWgBQAgAAAQAOQAQANAAAcQAAAdgTAQQgUAPgmAAQgNAAAAgKQAAgJALAAQASAAALgJQALgJAAgVQAAgUgLgKQgLgJgXAAQgKAAgEACQgFACgBADIgBANIgBAeIAAA+IABAoQABALACACIAHADQAIADAAAGQAAAGgHADQgIACgXAAQgWAAgIgCg");
	this.shape_23.setTransform(-10.5,-16.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E46").s().p("AhBBeQgHgGAAgJQAAgHAFgFQAFgFAHAAIAHABIAEADIAEAFQADAGADAAQAHAAAIgKQAHgLAAgLQAAgMgKgXIgBgDIgXgxIgNgcQgCgFgJgEQgFgCgBgCQgCgCAAgDQAAgGAHgCQAIgDAVAAQAUAAAHACQAHADAAAFIAAAFIgDACIgFADQgGACAAACIADALIAMAdIAKAaQAEAHACAAQACAAADgHIAJgWIALgcQADgKAAgEQAAgEgIgFQgIgEAAgEQAAgFAHgCQAGgCAQAAQARAAAGACQAGADAAAFQAAAGgIACIgGACQgIAEgJAYIgEALIgSAtQgYA7gOASQgPASgVAAQgKAAgHgGg");
	this.shape_24.setTransform(-34.3,-10.8);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#006E46").s().p("AAZBDIgIgHIgGADQgRALgRAAQgVAAgMgMQgOgMAAgTQAAgXARgMQAQgNAeAAQAHAAAEADQADACAAAFQAAAIgJAAQgOAAgJAGQgJAHAAAMQAAAMAIAGQAHAHANAAQANAAAGgGQAGgGAAgPIAAg1QAAgNgFgHQgGgGgJAAQgHAAgGADQgGADgGAGIgCAEQgKALgJAAQgFAAgEgEQgEgDAAgHQABgNAQgJQAQgJAaAAQAPAAAMAEQALAEAGAIQAFAFACAJQACAJAAAUIAAAtIAAAMQACAEADABIAEABQAKADgBAFQAAAGgJAGQgKAFgNAAQgGAAgHgHg");
	this.shape_25.setTransform(-48.9,-13.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#006E46").s().p("Ag+BWQgRgTAAgfQABgjATgUQATgWAeAAIAKABQAEABADADQACADAAAEQAAAIgJAAIgDgBIgFAAQgPAAgKANQgJAMAAAXQAAAXALAQQAJAPAQAAQAPAAAIgJQAIgIAAgQIAAgnIAAhBQAAgKgBgDQgCgEgGgCIgDgBQgJgDAAgFQAAgEADgCQAEgDAKgEIAQgFIAOgBQAEAAADACQACADAAAGIAAAIIgCBXIABA7QAAAOADACIAKADQAHACAAAFQAAAGgUAHIgPAEIgKABQgEAAgCgCQgCgCAAgFIAAgHIAAgDIgBgBIgFADIgFAFQgJAGgHADQgJADgIAAQgbAAgRgTg");
	this.shape_26.setTransform(-64.6,-16.8);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#006E46").s().p("AgYBmQgIgDAAgGQAAgFAHgCIAEgCQAEgCABgFQACgEAAgMIAAgJIAAgLIAAgPQAAgXgCgFQgBgHgCgCIgHgCQgJgDAAgFQAAgDADgDIAJgEIAVgHIAOgDQAEAAACADQACADAAAGIAAAJIgBAGIgBAkIAAAAIAAAjIABAUQABAFADACIAGACQAHADAAAFQAAAFgHADQgHACgTAAQgUAAgHgCgAgRhHQgGgFAAgHQAAgJAHgGQAHgFAJAAQAJAAAGAFQAGAGAAAHQAAAIgHAFQgHAGgJAAQgJAAgGgFg");
	this.shape_27.setTransform(-77.7,-16.8);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#006E46").s().p("AgXBmQgHgCAAgGQAAgFAGgCIAHgEQACgDABgIIABgcIAAgXIAAgaIAAgLQAAgjgBgLQgBgKgDgCIgJgDQgJgCAAgFQAAgEADgCQACgDALgDIATgGIANgCQAFAAABADQACADAAAGIAAALQgCAzAAAzIABAwQABALACACIAIAFQAHACAAAGQAAAFgHACQgHADgTAAQgVAAgGgDg");
	this.shape_28.setTransform(-85.8,-16.9);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#006E46").s().p("AgzA1QgUgVAAgfQAAggAVgVQAVgVAfAAQAfAAAUAUQATAUAAAfQAAAggVAWQgVAWgeAAQgfAAgUgVgAgbgqQgIAMAAATQAAAbAMATQAMATAQAAQAOAAAJgMQAIgLAAgUQAAgagMgTQgMgTgQAAQgOAAgJALg");
	this.shape_29.setTransform(-97.6,-13.6);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#006E46").s().p("AAfBkQgHgCAAgHQAAgFAJgEIAGgDQACgCABgJIACghIgBgUIgBgFQgBgDgIgBQgGgBgbAAIgeAAQgHABgDACIgCAFIAAAKIAAAMIABAhQABAJACACIAGADQAJAEAAAFQAAAHgIACQgHADgXAAQgWAAgIgDQgJgCABgHQAAgFAJgEIAGgDQADgCACgSIABg8IgBg1QgCgVgCgDQgBgCgIgDQgHgDAAgGQgBgGAHgCQAGgCAaAAQAZAAAGACQAHACAAAGQAAAGgJADIgGADQgCACgCAJIAAAqQAAAGAFACQAFACAVAAIALAAIAegBQAJgBACgCIACgDIABgFIAAgHIgCgjQgBgHgCgCIgGgDQgJgDAAgGQAAgGAGgCQAIgCAYAAQAZAAAHACQAGACABAGQAAAGgJADIgHADQgDACgBAUQgBATAAAmIABA2QABAWACADQABACAIADQAHADABAFQAAAHgJACQgIADgWAAQgXAAgIgDg");
	this.shape_30.setTransform(-116.3,-16.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.HOLIDAYPLATTERS, new cjs.Rectangle(-129.1,-35.8,258.3,71.6), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("A2aygMAs1AAAMAAAAlBMgs1AAAg");
	this.shape.setTransform(0,0,1.042,1.051);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-150.5,-125.5,301,251), null);


(lib.decplattersbitesbottomright = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.nineteenbottomright();
	this.instance.parent = this;
	this.instance.setTransform(-88.5,-55);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.decplattersbitesbottomright, new cjs.Rectangle(-88.5,-55,147,113), null);


(lib.ctarollovervid = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AnLCpQhGAAgygyQgxgxAAhGIAAAAQAAhFAxgyQAygxBGAAIOXAAQBGAAAxAxQAyAyAABFIAAAAQAABGgyAxQgxAyhGAAg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarollovervid, new cjs.Rectangle(-62.8,-16.8,125.8,33.8), null);


(lib.crowdpleasingcheese = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E46").s().p("AgKBKIgPgDIgEADIgFABIgDgBIgDgCQgEgEgEgLQgFgMAAgKQAAgFADgDQACgDAEAAQAHAAAGALIAGAJQAEAGAHADQAIADAHAAQAKAAAFgEQAGgFAAgIQAAgMgXgMIgJgEQgWgLgIgIQgHgJAAgOQAAgSAMgMQANgMAVAAIAJABIAKACIAHgDIAEgBQAHAAAHALQAHAMAAAMQAAAFgDADQgCADgEAAQgDAAgDgDQgDgDgFgHQgFgJgGgDQgGgDgHAAQgIAAgFAEQgFAFAAAHQAAAHAFAFQAFAFARAJIACABQAoASAAAXQAAAUgQANQgPAOgXAAg");
	this.shape.setTransform(92,20.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E46").s().p("AgqBGQgHgCAAgGQAAgFAHgDIADgBQAEgCACgFQABgFAAgKIAAgKIAAgMIAAgIQAAgZgBgIQgBgIgDgCIgHgDQgJgCAAgFQAAgDADgCQADgDAGgDIATgFIANgDQAHAAACATIAAADIABABQAHgMAIgGQAIgGAIAAQAKAAAGAGQAGAGAAAKQAAAKgFAFQgEAGgIAAIgIgBIgGgFIgDgFQAAgBgBgBQAAAAAAgBQgBAAAAAAQAAgBgBAAQgKAAgEAOQgDANAAArQAAANABAFQACAHAEABIAFACQAJADAAAGQAAAFgIACQgIADgTAAQgVAAgHgDg");
	this.shape_1.setTransform(80.9,20.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_2.setTransform(67.6,20.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E46").s().p("AgHBWQgHgDgFgFQgFgEgCgIQgCgHAAgWIAAhMIgNAAIgEAAIgCgEIAAgEQAAgEAPgNIAGgFIAGgFQAOgNAGAAIADACQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIAAAaIAgAAQADABACABQABABAAAEIAAADQAAAFgBABQgCABgDAAIgdAAIgDACIAAADIAABGQAAASADAFQADAFAIgBQAFAAAHgCIAJgCQADAAADACQAAAAABABQAAAAAAABQABAAAAABQAAABAAABQAAAHgMAHQgNAIgPAAQgIAAgHgCg");
	this.shape_3.setTransform(55.1,18.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E46").s().p("AgHBWQgHgDgFgFQgFgEgCgIQgCgHAAgWIAAhMIgNAAIgEAAIgCgEIAAgEQAAgEAPgNIAGgFIAGgFQAOgNAGAAIADACQABAAAAAAQAAAAABABQAAAAAAABQAAAAAAABIAAAaIAgAAQADABACABQABABAAAEIAAADQAAAFgBABQgCABgDAAIgdAAIgDACIAAADIAABGQAAASADAFQADAFAIgBQAFAAAHgCIAJgCQADAAADACQAAAAABABQAAAAAAABQAAAAABABQAAABAAABQAAAHgMAHQgNAIgPAAQgIAAgHgCg");
	this.shape_4.setTransform(45,18.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E46").s().p("AAZBDIgHgHIgGADQgRALgSAAQgVAAgNgMQgNgMABgTQAAgXAQgMQARgNAeAAQAGAAADADQAEACAAAFQAAAIgKAAQgNAAgJAGQgIAHAAAMQAAAMAHAGQAIAHAMAAQANAAAGgGQAGgGAAgPIAAg1QAAgNgGgHQgFgGgJAAQgHAAgGADQgGADgFAGIgEAEQgJALgJAAQgGAAgDgEQgDgDAAgHQAAgNAQgJQARgJAZAAQAQAAALAEQAMAEAFAIQAFAFABAJQACAJAAAUIAAAtIABAMQACAEADABIAEABQAJADAAAFQABAGgKAGQgKAFgMAAQgHAAgHgHg");
	this.shape_5.setTransform(32.5,20.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E46").s().p("AgXBmQgHgCAAgGQAAgFAGgCIAHgEQACgDABgIIABgcIAAgXIAAgaIAAgLQAAgjgBgLQgBgKgDgCIgJgDQgJgCAAgFQAAgEADgCQACgDALgDIATgGIANgCQAFAAABADQACADAAAGIAAALQgCAzAAAzIABAwQABALACACIAIAFQAHACAAAGQAAAFgHACQgHADgTAAQgVAAgGgDg");
	this.shape_6.setTransform(20.5,16.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E46").s().p("AhJBlQgIgCAAgHQAAgGAJgDIAGgDQADgCACgSIABg9IgBg1QgCgVgBgCQgCgCgHgEQgIgDAAgFQAAgFAEgDQAFgCAJgBIAOAAIARABIAcgBIAWAAQAgAAAQANQAQANAAAcQAAAegTAPQgUAPgmAAQgNAAAAgJQAAgKALAAQASAAALgJQALgJAAgWQAAgTgLgJQgLgKgXAAQgKAAgEACQgFABgBAFIgBAMIgBAeIAAA+IABApQABAKACACIAHADQAIADAAAGQAAAHgHACQgIACgXABQgWgBgIgCg");
	this.shape_7.setTransform(8.6,17);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_8.setTransform(-15.7,20.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E46").s().p("AgKBKIgPgDIgEADIgFABIgDgBIgDgCQgEgEgEgLQgFgMAAgKQAAgFADgDQACgDAEAAQAHAAAGALIAGAJQAEAGAHADQAIADAHAAQAKAAAFgEQAGgFAAgIQAAgMgXgMIgJgEQgWgLgIgIQgHgJAAgOQAAgSAMgMQANgMAVAAIAJABIAKACIAHgDIAEgBQAHAAAHALQAHAMAAAMQAAAFgDADQgCADgEAAQgDAAgDgDQgDgDgFgHQgFgJgGgDQgGgDgHAAQgIAAgFAEQgFAFAAAHQAAAHAFAFQAFAFARAJIACABQAoASAAAXQAAAUgQANQgPAOgXAAg");
	this.shape_9.setTransform(-29.5,20.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_10.setTransform(-43,20.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABAAAAgBQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_11.setTransform(-58,20.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E46").s().p("AAUBmQgHgCAAgFQAAgGAHgCIAFgDQADgCACgGIABgVQAAgugGgLQgFgLgQAAQgGAAgHAEQgHAFgEAHQgDAGgBALIgBAnQAAAOABAFQABAEADACIAGADQAGACABAGQAAAFgHACQgHACgTABQgWgBgHgCQgGgDgBgFQABgFAGgDIAEgBQAEgCACgGQABgHAAgPIAAgXIAAgWIgBhAQgBgPgCgEQgBgBgJgCQgJgDAAgFQAAgEAEgDQAEgDANgEIANgEIAOgBQAEAAACACQADADAAAGIgBAGIgBA5IAAAHIABADIACABIADgCIAFgHQAHgGAIgEQAHgEAJABQAYAAAMAPQANAQAAAgIAAAMIAAAaIAAAIQAAAIABACQABAEADACIAFABQAGADABAFQgBAFgGADQgHACgXABQgSgBgHgCg");
	this.shape_12.setTransform(-74.2,16.9);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E46").s().p("AgVBjQgTgHgPgNQgQgPgJgVQgJgVAAgYQAAgUAGgRQAGgRALgOQAOgRAUgJQAUgJAXAAIARABIAcAGIADgBIALgCIAFABIADAEQAFAIADALQADALAAAIQAAAGgCADQgCADgFAAQgGAAgLgNIgJgKQgIgIgLgEQgLgEgOAAQgbAAgQATQgQATAAAhQAAAqAUAbQAVAbAeAAQANAAALgEQALgFAHgHIAHgIQAGgIAEAAQAEAAADAEQACAEAAAGQAAAOgEAHQgEAIgGAAIgBAAIgDgBQgNAHgNAEQgNADgPAAQgUAAgTgHg");
	this.shape_13.setTransform(-92.1,17.1);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E46").s().p("Ag0BdQgSgLAAgPQAAgIAEgEQADgFAIAAQAGAAAEADQADADACAIQADAJAJAGQAJAHARgBQASABANgIQANgHAAgLQAAgHgFgDQgFgEgJAAIgQABIgVACQgaAAgNgJQgOgJAAgLQAAgHAFgHQAFgGAKgGQgIgIgEgJQgEgJAAgLQAAgXARgQQASgPAaAAIAOACIAWADQAGABAGgDQAGgCAJgHIAFAEIABAFQAAAGgEAGQgFAGgIAEIAEAMIACALQAAAYgSAOQgRAOgbABIgPgBIgOgDIgEAFIgCAFQAAAHAHADQAHADAOAAIAVgBIAWgCQAUAAAKAIQALAIAAAPQAAAXgWAPQgXAPghAAQgbAAgSgLgAgXhGQgHAKAAANQAAAPAHAJQAHAJAMAAQALAAAIgJQAIgJAAgPQAAgOgIgJQgIgJgLAAQgLAAgIAJg");
	this.shape_14.setTransform(95,-11.2);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E46").s().p("AhFBHQgHgDAAgGQgBgFAIgCIADgCQAEgCACgFQABgEAAgMIAAgJIAAgLIAAgOQAAgXgBgGQgBgHgDgCIgHgCQgJgDABgFQAAgDACgDIAJgEIAUgHIAPgCQAEAAACACQACACAAAFIAAAJIAAACIABAAIABAAIAAgBIADgDIAEgDQAPgOARAAQAKAAAKAEQAJAFAHAHQAGAIADALQADALAAAXIAAASIAAAJIAAAIQAAALABAEQABAEAEACIAEACQAGACABAFQAAAGgHADQgHACgVAAQgUAAgHgCQgHgDAAgFQAAgFAIgDIAEgCQAEgDACgFIAAgWQAAgtgFgLQgGgLgPAAQgGgBgIAFQgGAEgEAJQgDAGgBAKQgCALAAAcQAAAOACAFQABAEACACIAGACQAHADAAAFQAAAFgHADQgHACgTAAQgVAAgHgCg");
	this.shape_15.setTransform(78.4,-13.7);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E46").s().p("AgYBmQgIgDAAgGQAAgFAHgCIAEgCQAEgCABgFQACgEAAgMIAAgJIAAgLIAAgPQAAgXgCgFQgBgHgCgCIgHgCQgJgDAAgFQAAgDADgDIAJgEIAVgHIAOgDQAEAAACADQACADAAAGIAAAJIgBAGIgBAkIAAAAIAAAjIABAUQABAFADACIAGACQAHADAAAFQAAAFgHADQgHACgTAAQgUAAgHgCgAgRhHQgGgFAAgHQAAgJAHgGQAHgFAJAAQAJAAAGAFQAGAGAAAHQAAAIgHAFQgHAGgJAAQgJAAgGgFg");
	this.shape_16.setTransform(65.9,-16.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#006E46").s().p("AgKBKIgPgDIgEADIgFABIgDgBIgDgCQgEgEgEgLQgFgMAAgKQAAgFADgDQACgDAEAAQAHAAAGALIAGAJQAEAGAHADQAIADAHAAQAKAAAFgEQAGgFAAgIQAAgMgXgMIgJgEQgWgLgIgIQgHgJAAgOQAAgSAMgMQANgMAVAAIAJABIAKACIAHgDIAEgBQAHAAAHALQAHAMAAAMQAAAFgDADQgCADgEAAQgDAAgDgDQgDgDgFgHQgFgJgGgDQgGgDgHAAQgIAAgFAEQgFAFAAAHQAAAHAFAFQAFAFARAJIACABQAoASAAAXQAAAUgQANQgPAOgXAAg");
	this.shape_17.setTransform(55.7,-13.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#006E46").s().p("AAZBDIgIgHIgFADQgRALgSAAQgVAAgMgMQgNgMAAgTQAAgXAQgMQAQgNAfAAQAGAAAEADQADACAAAFQAAAIgKAAQgNAAgJAGQgJAHABAMQgBAMAIAGQAHAHANAAQANAAAGgGQAGgGAAgPIAAg1QAAgNgFgHQgGgGgJAAQgHAAgGADQgGADgGAGIgDAEQgJALgJAAQgGAAgDgEQgEgDABgHQAAgNAQgJQAQgJAaAAQAPAAAMAEQAMAEAFAIQAFAFACAJQABAJAAAUIAAAtIABAMQACAEADABIAEABQAKADgBAFQAAAGgJAGQgKAFgMAAQgHAAgHgHg");
	this.shape_18.setTransform(42.2,-13.6);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#006E46").s().p("AguA2QgUgVAAgfQAAggAVgWQAVgVAfAAQAcAAAQAPQAQAQAAAbQAAAIgDADQgCADgLAAIg2AAQgFAAgCgCQgDgDAAgDQAAgEADgCQACgCAFAAIAdAAIAHgBQABgBAAAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgNgJgKQgJgJgNAAQgRAAgIAPQgIAPAAAUQAAAWALAQQAMAQARAAQAKAAAIgCQAHgCAHgFIAFgEQAHgGAEAAQADAAACACQACACAAADQAAADgDAFQgEAFgGAFQgMAKgMAFQgLAEgOAAQgdAAgVgUg");
	this.shape_19.setTransform(26.9,-13.6);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#006E46").s().p("AgXBmQgHgCAAgGQAAgFAGgCIAHgEQACgDABgIIABgcIAAgXIAAgaIAAgLQAAgjgBgLQgBgKgDgCIgJgDQgJgCAAgFQAAgEADgCQACgDALgDIATgGIANgCQAFAAABADQACADAAAGIAAALQgCAzAAAzIABAwQABALACACIAIAFQAHACAAAGQAAAFgHACQgHADgTAAQgVAAgGgDg");
	this.shape_20.setTransform(15.2,-16.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#006E46").s().p("AhJBlQgIgDAAgGQAAgGAJgDIAGgDQADgCACgRIABg9IgBg2QgCgUgBgEQgCgBgHgDQgIgDAAgGQAAgFAEgDQAFgDAJAAIAOAAIARABIAcgBIAWgBQAgAAAQAOQAQANAAAcQAAAdgTAQQgUAPgmAAQgNAAAAgKQAAgJALAAQASAAALgJQALgJAAgVQAAgUgLgKQgLgJgXAAQgKAAgEACQgFACgBADIgBANIgBAeIAAA+IABAoQABALACACIAHADQAIADAAAGQAAAGgHADQgIACgXAAQgWAAgIgCg");
	this.shape_21.setTransform(3.3,-16.8);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#006E46").s().p("AgiANQgBgCAAgEIABgGIADgIQACgDACgBQACgCAGAAIAHAAIAMABIAYgBIAEgBQAEAAADACQABACAAADQAAAHgEAHQgEAHgHAAIgHAAIgIAAIgfABIgCAAQgFAAgCgCg");
	this.shape_22.setTransform(-10.5,-13.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#006E46").s().p("Ag9BWQgSgTABgfQAAgjATgUQATgWAeAAIAKABQAEABADADQACADAAAEQAAAIgJAAIgEgBIgDAAQgQAAgJANQgKAMAAAXQAAAXAKAQQALAPAQAAQAOAAAIgJQAIgIAAgQIAAgnIAAhBQAAgKgCgDQgCgEgFgCIgEgBQgJgDAAgFQABgEADgCQAEgDAKgEIAQgFIANgBQAGAAABACQACADAAAGIAAAIIgCBXIABA7QACAOACACIAKADQAIACgBAFQABAGgWAHIgNAEIgMABQgEAAgBgCQgCgCAAgFIAAgHIAAgDIgBgBIgEADIgHAFQgIAGgIADQgHADgJAAQgbAAgQgTg");
	this.shape_23.setTransform(-23.3,-16.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#006E46").s().p("AAIAPIgRgsQgHgUgHgDIgEgCQgJgDAAgFQABgGAGgCQAIgCAWgBQATABAHACQAHACAAAGIgBAEIgCACIgFADQgGACAAADIADAJIALAeIANAbQADAHABgBQACAAADgDIAGgNIAPgjQAGgOAAgFIgCgEIgDgEIgDgCQgHgCAAgEQAAgGAHgCQAFgCASgBQAPABAHACQAFACAAAFQABAGgIACIgFACQgGADgNAeIgEAHIgFANQghBJgJABQgKgBgZg6gAhTAIIgEgJIgJgXQgJgZgHgDIgEgCQgJgDAAgFQAAgGAIgCQAHgCAXgBQAUABAHACQAGACAAAGIgBAEIgCACIgFADQgGACAAADIADAMIALAbIAMAbQADAGACAAQAFABADgJIAGgLIACgDQACgCAEAAQADAAACACQACACAAADQAAAEgEAIQgOAhgHALQgHAKgFABQgKAAgchCg");
	this.shape_24.setTransform(-43.7,-13.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#006E46").s().p("AgzA1QgUgVAAgfQAAggAVgVQAVgVAfAAQAfAAAUAUQATAUAAAfQAAAggVAWQgVAWgeAAQgfAAgUgVgAgbgqQgIAMAAATQAAAbAMATQAMATAQAAQAOAAAJgMQAIgLAAgUQAAgagMgTQgMgTgQAAQgOAAgJALg");
	this.shape_25.setTransform(-63.6,-13.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#006E46").s().p("AgqBHQgHgDAAgGQAAgFAHgCIADgCQAEgCACgFQABgEAAgMIAAgJIAAgLIAAgJQAAgZgBgIQgBgIgDgCIgHgCQgJgDAAgFQAAgDADgDQADgCAGgCIATgHIANgCQAHAAACATIAAADIABAAQAHgLAIgGQAIgGAIAAQAKAAAGAGQAGAGAAAKQAAAKgFAGQgEAFgIAAIgIgBIgGgEIgDgGQAAgBAAgBQgBAAAAgBQgBAAAAAAQAAAAgBAAQgKAAgEANQgDAOAAAqQAAAMABAHQACAGAEACIAFACQAJACAAAGQAAAFgIADQgIACgTAAQgVAAgHgCg");
	this.shape_26.setTransform(-76.7,-13.7);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#006E46").s().p("AgVBjQgTgHgPgNQgQgPgJgVQgJgVAAgYQAAgUAGgRQAGgRALgOQAOgRAUgJQAUgJAXAAIARABIAcAGIADgBIALgCIAFABIADAEQAFAIADALQADALAAAIQAAAGgCADQgCADgFAAQgGAAgLgNIgJgKQgIgIgLgEQgLgEgOAAQgbAAgQATQgQATAAAhQAAAqAUAbQAVAbAeAAQANAAALgEQALgFAHgHIAHgIQAGgIAEAAQAEAAADAEQACAEAAAGQAAAOgEAHQgEAIgGAAIgBAAIgDgBQgNAHgNAEQgNADgPAAQgUAAgTgHg");
	this.shape_27.setTransform(-92.1,-16.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.crowdpleasingcheese, new cjs.Rectangle(-104,-35.8,208.2,71.6), null);


(lib.nineteenrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// Layer 1
	this.instance = new lib.ctarollovervid();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-62.8,-16.8,125.8,33.8);


(lib.buttonmain = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.square("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(0.1,0);
	this.instance._off = true;
	this.instance.filters = [new cjs.ColorFilter(0, 0, 0, 1, 0, 110, 71, 0)];
	this.instance.cache(-153,-128,306,256);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


// stage content:
(lib.squarenineteen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_49 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_247 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(49).call(this.frame_49).wait(198).call(this.frame_247).wait(8));

	// button
	this.btn_main = new lib.buttonmain();
	this.btn_main.parent = this;
	this.btn_main.setTransform(149.5,124.2);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.buttonmain(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(255));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(255));

	// white-square
	this.instance_1 = new lib.whitesquare();
	this.instance_1.parent = this;
	this.instance_1.setTransform(153,126.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(246));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("A5LafMAAAg0+MA0iAAAMAAAA0+g");
	mask.setTransform(175.1,110.6);

	// get-party-started
	this.instance_2 = new lib.partystarted();
	this.instance_2.parent = this;
	this.instance_2.setTransform(97.8,66.8);
	this.instance_2.alpha = 0;

	var maskedShapeInstanceList = [this.instance_2];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(211).to({x:-127.2,alpha:1},0).to({x:103.8},10,cjs.Ease.get(1)).to({x:97.8},8,cjs.Ease.get(1)).wait(26));

	// mask (mask)
	var mask_1 = new cjs.Shape();
	mask_1._off = true;
	mask_1.graphics.p("A5LafMAAAg0+MA0iAAAMAAAA0+g");
	mask_1.setTransform(175.1,110.6);

	// holidayplatters-small-bites
	this.instance_3 = new lib.HOLIDAYPLATTERS();
	this.instance_3.parent = this;
	this.instance_3.setTransform(142.9,107.2);
	this.instance_3.alpha = 0;

	var maskedShapeInstanceList = [this.instance_3];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_1;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(211).to({x:-82.1},0).to({x:147.9,alpha:1},10,cjs.Ease.get(1)).to({x:142.9},8,cjs.Ease.get(1)).wait(26));

	// ready-to-serve
	this.instance_4 = new lib.readyserveshrimp();
	this.instance_4.parent = this;
	this.instance_4.setTransform(115.6,95.3);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(147).to({alpha:1},10).wait(40).to({alpha:0},5).wait(53));

	// party-perfect
	this.instance_5 = new lib.partyperfectcrudite();
	this.instance_5.parent = this;
	this.instance_5.setTransform(108.1,95.3);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(97).to({alpha:1},10).wait(40).to({alpha:0},5).wait(103));

	// mask (mask)
	var mask_2 = new cjs.Shape();
	mask_2._off = true;
	mask_2.graphics.p("A5LafMAAAg0+MA0iAAAMAAAA0+g");
	mask_2.setTransform(175.1,110.6);

	// crowd-pleasing-cheese
	this.instance_6 = new lib.crowdpleasingcheese();
	this.instance_6.parent = this;
	this.instance_6.setTransform(117.9,95.3);
	this.instance_6.alpha = 0;

	var maskedShapeInstanceList = [this.instance_6];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_2;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(37).to({x:-107.1},0).to({x:127.9,alpha:1},10,cjs.Ease.get(1)).to({x:117.9},8,cjs.Ease.get(1)).wait(42).to({alpha:0},5).wait(153));

	// kale-logo
	this.instance_7 = new lib.logokale();
	this.instance_7.parent = this;
	this.instance_7.setTransform(250.8,32.8,0.003,0.003);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(9).to({scaleX:0.24,scaleY:0.24,alpha:1},6,cjs.Ease.get(1)).to({regY:0.2,scaleX:0.22,scaleY:0.22},7,cjs.Ease.get(1)).wait(233));

	// mask (mask)
	var mask_3 = new cjs.Shape();
	mask_3._off = true;
	mask_3.graphics.p("A2ZafMAAAg0+MAxwAAAMAAAA0+g");
	mask_3.setTransform(175.1,110.6);

	// shop-now
	this.instance_8 = new lib.shopnow();
	this.instance_8.parent = this;
	this.instance_8.setTransform(74.1,161.5);
	this.instance_8.alpha = 0;

	var maskedShapeInstanceList = [this.instance_8];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_3;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(49).to({x:-70.9},0).to({x:84.1,alpha:1},10,cjs.Ease.get(1)).to({x:74.1},8,cjs.Ease.get(1)).wait(188));

	// mask (mask)
	var mask_4 = new cjs.Shape();
	mask_4._off = true;
	mask_4.graphics.p("A5LafMAAAg0+MA0iAAAMAAAA0+g");
	mask_4.setTransform(175.1,110.6);

	// cta-rollover
	this.cta_rollover = new lib.nineteenrollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(76.7,162.4);
	this.cta_rollover.alpha = 0;

	var maskedShapeInstanceList = [this.cta_rollover];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_4;
	}

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(49).to({x:-68.3},0).to({x:86.7,alpha:1},10,cjs.Ease.get(1)).to({x:76.7},8,cjs.Ease.get(1)).wait(188));

	// mask (mask)
	var mask_5 = new cjs.Shape();
	mask_5._off = true;
	mask_5.graphics.p("A5LafMAAAg0+MA0iAAAMAAAA0+g");
	mask_5.setTransform(175.1,110.6);

	// cta-rectangle
	this.instance_9 = new lib.rectanglenineteen();
	this.instance_9.parent = this;
	this.instance_9.setTransform(76.7,162.4);
	this.instance_9.alpha = 0;

	var maskedShapeInstanceList = [this.instance_9];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask_5;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(49).to({x:-68.3},0).to({x:86.7,alpha:1},10,cjs.Ease.get(1)).to({x:76.7},8,cjs.Ease.get(1)).wait(188));

	// bottom-left
	this.instance_10 = new lib.squarebottomleftholidayplatters();
	this.instance_10.parent = this;
	this.instance_10.setTransform(60,204.5);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(9).to({alpha:1},10).wait(236));

	// bottom-right
	this.instance_11 = new lib.decplattersbitesbottomright();
	this.instance_11.parent = this;
	this.instance_11.setTransform(241.5,192);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(13).to({alpha:1},10).wait(232));

	// top-right
	this.instance_12 = new lib.nineteentopright_1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(265,62.5);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(19).to({alpha:1},10).wait(226));

	// crackers
	this.instance_13 = new lib.nineteencrackers_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(150.5,18.5);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(23).to({alpha:1},10).wait(222));

	// top-left
	this.instance_14 = new lib.nineteentopleft_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(60,30.5);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(29).to({alpha:1},10).wait(216));

	// table-tan
	this.instance_15 = new lib.nineteentable_1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(255));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(144.1,118.1,318,266);
// library properties:
lib.properties = {
	id: '92879F2740E34FB9890B82961B713FEA',
	width: 300,
	height: 250,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['92879F2740E34FB9890B82961B713FEA'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;